### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by illiliti** [illiliti/king#1]
- https://k1sslinux.org/package-system
- https://k1sslinux.org/package-manager
- https://github.com/dylanaraps/k/blob/master/README

**Suggestions and ideas are greatly appreciated!**

* docs
  * [ ] document environment variables
  * [ ] document usage (with examples!!!)
  * [ ] document supported archive formats
  * [ ] document differences between kiss and king(there is a lot)
  * [ ] document the whole codebase (including unit tests)
* common
  * [ ] setup CI
  * [ ] unit tests
    * [ ] alternative.go
    * [ ] build.go
    * [x] dependency.go
    * [ ] download.go
    * [x] extract.go
    * [ ] install.go
    * [x] package.go
    * [ ] remove.go
    * [x] source.go
    * [x] tarball.go
    * [ ] update.go
    * [x] validate.go
    * [x] verify.go
    * [x] version.go
    * [ ] cmd/king
      * [ ] build.go
      * [ ] checksum.go
      * [ ] download.go
      * [ ] install.go
      * [ ] main.go
      * [ ] query.go
      * [ ] remove.go
      * [ ] swap.go
      * [ ] update.go
    * [ ] internal
      * [ ] archive
      * [ ] cleanup
      * [ ] cp
  * [ ] improve logging
  * [x] improve error messages
  * [ ] rework debugging stuff. debugging should be effortless if possible
  * [ ] drop replace in go.mod. depends on https://github.com/mholt/archiver/pull/265
* future
  * [ ] hooks?
  * [ ] man pages
  * [ ] extensions
  * [ ] binary packages?
  * [ ] repository signing?
  * [ ] proper orphans system
  * [ ] root-less chroot builds?
    - It's impossible to achieve without resorting to dirty hacks like exec'ing yourself
    - https://github.com/golang/go/issues/12125
    - https://github.com/golang/go/issues/22283
    - https://github.com/u-root/u-root/blob/707f919d5c668ef1a05d66676c6fdaaa08e10a70/cmds/core/unshare/unshare.go#L11
  * [ ] make library code fully thread-safe?
  * [ ] /var/db/kiss/installed as a git repository?
  * [x] errors.New() vs fmt.Errorf() vs custom Error()
  * [x] switch actions to getopt-like flags with subcommands
  * [ ] implement privilege elevation mess? is it really needed?
  * [x] replace list and search actions with query action like in xbps
* action
  * [x] main
    * [ ] guard against running multiple instances at the same time.
  * [x] build
    * [ ] progress bar 
    * [ ] build log
      * [x] stdout
      * [ ] file
  * [x] checksum
  * [x] download
    * [ ] progress bar
    * [ ] parallel downloads
  * [x] install
  * [x] query
    * [ ] fix https://github.com/go-git/go-git/issues/137
  * [x] remove
  * [x] swap
  * [x] update
* library
  * [x] alternative
    * [x] allow swapping by only using path 
  * [x] build
    * [x] dynamic dependencies based on ldd-like output
    * [ ] strip binaries using pure go (will be implemented as a standalone project)
      - That would be harder than i thought because i need to reimplement entire debug/elf with READ/SEEK/WRITE abilities + ar library. Anyway, i have no choice to not to do that!
    * [x] remove .la and charset.alias
    * [ ] add a way to resume build
    * [x] handle ctrl+c
      - How about using context.Context to allow more flexibility?
    * [ ] allow selecting which files should be stripped via special `nostrip` file.
  * [x] config
    * [x] cache reverse dependencies for faster lookups
    * [x] cache manifests of installed packages for faster finding package by path
  * [x] dependency
    * [x] rewrite RecursiveDependencies() 
      * [x] guard against circular dependencies
      * [x] properly handle make dependencies
    * [x] guard against depending on itself
  * [x] download
  * [x] install
    * [x] add a way to forcefully overwrite files in /etc/
    * [ ] guard against incomplete installation (due to ctrl+c, shutdown, ...)
    * [ ] directly extract tarball into / without using temporary directory
  * [x] package
    * [x] find by name
    * [x] find by path
    * [ ] check required files (build, version, ...)
  * [x] extract
    * [x] git clone commit/branch
    * [ ] progress bar
  * [x] remove
    * [x] add a way to forcefully remove files in /etc/
    * [ ] guard against incomplete removal (due to ctrl+c, shutdown, ...)
  * [x] source
    * [x] handle https
    * [x] handle git
      * [x] commit
      * [x] branch
    * [x] handle absolute/relative files
    * [ ] ban VERSION, MAJOR, MINOR, ... variables support
  * [x] tarball
    * [x] find pre-built tarball by path
    * [x] find pre-built tarball by package name 
  * [x] update
    * [x] optionally exclude packages from update
    * [x] add a way to skip updating repositories
    * [ ] fix https://github.com/go-git/go-git/issues/37
  * [x] validate
    * [ ] move errors into ValidateError struct?
  * [x] verify
    - SKIP support will not be added. Instead, it will be banned at all. People should use --no-verify option to temporary disable checksums for debugging purposes. Checksums are completely mandatory now.
  * [x] version
* completion
  * [ ] zsh
  * [ ] ...

**Comment by sdsddsd1** [comment]
I had the idea for parallel downloads. E.g when downloading a bunch of source files, download them parallel instead of one after the other to safe time.
Maybe this is easier to accomplish on a more complex language.

**Comment by illiliti** [comment]
Thanks! Yeah, this is already in TODO(action->download). I also want to asynchronously download package sources while other packages in the progress of building. This is complex to implement because this will introduce a lot of synchronization.
